<?php
/**
 * Tradução de rótulos de categorias da API de afiliados AliExpress (inglês → PT-BR).
 * Inclui mapeamentos completos frequentes + substituição por palavras.
 */
function aliexpressTraduzirTituloCategoria(string $en): string {
    $en = trim($en);
    if ($en === '') {
        return '';
    }
    $chave = mb_strtolower($en, 'UTF-8');
    static $completas = [
        'women\'s clothing' => 'Roupas femininas',
        'men\'s clothing' => 'Roupas masculinas',
        'mother & kids' => 'Mãe e bebê',
        'mother and kids' => 'Mãe e bebê',
        'toys & hobbies' => 'Brinquedos e hobbies',
        'toys and hobbies' => 'Brinquedos e hobbies',
        'phones & telecommunications' => 'Celulares e telecomunicações',
        'phones and telecommunications' => 'Celulares e telecomunicações',
        'computer & office' => 'Informática e escritório',
        'computer and office' => 'Informática e escritório',
        'consumer electronics' => 'Eletrônicos',
        'home & garden' => 'Casa e jardim',
        'home and garden' => 'Casa e jardim',
        'home appliances' => 'Eletrodomésticos',
        'jewelry & accessories' => 'Joias e acessórios',
        'jewelry and accessories' => 'Joias e acessórios',
        'watches' => 'Relógios',
        'shoes' => 'Calçados',
        'bags & shoes' => 'Bolsas e calçados',
        'bags and shoes' => 'Bolsas e calçados',
        'luggage & bags' => 'Malas e bolsas',
        'luggage and bags' => 'Malas e bolsas',
        'beauty & health' => 'Beleza e saúde',
        'beauty and health' => 'Beleza e saúde',
        'hair extensions & wigs' => 'Extensões de cabelo e perucas',
        'hair extensions and wigs' => 'Extensões de cabelo e perucas',
        'sports & entertainment' => 'Esportes e lazer',
        'sports and entertainment' => 'Esportes e lazer',
        'outdoor fun & sports' => 'Ar livre e esportes',
        'automobiles, parts & accessories' => 'Automóveis, peças e acessórios',
        'automobiles, parts and accessories' => 'Automóveis, peças e acessórios',
        'automobiles & motorcycles' => 'Automóveis e motocicletas',
        'automobiles and motorcycles' => 'Automóveis e motocicletas',
        'tools & industrial' => 'Ferramentas e industrial',
        'tools and industrial' => 'Ferramentas e industrial',
        'home improvement' => 'Reforma e construção',
        'lights & lighting' => 'Iluminação',
        'lights and lighting' => 'Iluminação',
        'furniture' => 'Móveis',
        'pet products' => 'Produtos para pets',
        'office & school supplies' => 'Material de escritório e escolar',
        'office and school supplies' => 'Material de escritório e escolar',
        'education & office supplies' => 'Educação e material de escritório',
        'education and office supplies' => 'Educação e material de escritório',
        'weddings & events' => 'Casamentos e eventos',
        'weddings and events' => 'Casamentos e eventos',
        'novelty & special use' => 'Novidades e uso especial',
        'novelty and special use' => 'Novidades e uso especial',
        'underwear' => 'Roupas íntimas',
        'apparel accessories' => 'Acessórios de vestuário',
        'bottoms' => 'Partes de baixo (calças, saias)',
        'tops & sets' => 'Partes de cima e conjuntos',
        'tops and sets' => 'Partes de cima e conjuntos',
        'dresses' => 'Vestidos',
        'muslim fashion' => 'Moda muçulmana',
        'world apparel' => 'Vestuário mundial',
        'cellphones & telecommunications' => 'Celulares e telecomunicações',
        'cellphones and telecommunications' => 'Celulares e telecomunicações',
        'mobile phone accessories' => 'Acessórios para celular',
        'mobile phones' => 'Celulares',
        'tablet pc & accessories' => 'Tablets e acessórios',
        'tablet pc and accessories' => 'Tablets e acessórios',
        'laptops' => 'Notebooks',
        'desktops' => 'Computadores de mesa',
        'computer peripherals' => 'Periféricos de computador',
        'storage devices' => 'Armazenamento',
        'networking' => 'Redes',
        'components' => 'Componentes',
        'kitchen,dining & bar' => 'Cozinha, refeições e bar',
        'kitchen, dining & bar' => 'Cozinha, refeições e bar',
        'kitchen,dining and bar' => 'Cozinha, refeições e bar',
        'textile & home fabric' => 'Têxteis e tecidos para casa',
        'textile and home fabric' => 'Têxteis e tecidos para casa',
        'festive & party supplies' => 'Festas e comemorações',
        'festive and party supplies' => 'Festas e comemorações',
        'arts,crafts & sewing' => 'Artes, artesanato e costura',
        'arts, crafts & sewing' => 'Artes, artesanato e costura',
        'arts,crafts and sewing' => 'Artes, artesanato e costura',
    ];
    if (isset($completas[$chave])) {
        return $completas[$chave];
    }
    $s = str_ireplace([' & ', ' and '], [' e ', ' e '], $en);
    $palavras = [
        'women\'s' => 'Feminino',
        'womens' => 'Feminino',
        'men\'s' => 'Masculino',
        'mens' => 'Masculino',
        'kids' => 'Infantil',
        'baby' => 'Bebê',
        'mother' => 'Mãe',
        'clothing' => 'roupas',
        'apparel' => 'vestuário',
        'shoes' => 'calçados',
        'bags' => 'bolsas',
        'jewelry' => 'joias',
        'watches' => 'relógios',
        'beauty' => 'beleza',
        'health' => 'saúde',
        'sports' => 'esportes',
        'toys' => 'brinquedos',
        'hobbies' => 'hobbies',
        'electronics' => 'eletrônicos',
        'phones' => 'telefones',
        'telecommunications' => 'telecomunicações',
        'computer' => 'computador',
        'office' => 'escritório',
        'home' => 'casa',
        'garden' => 'jardim',
        'furniture' => 'móveis',
        'lighting' => 'iluminação',
        'automobiles' => 'automóveis',
        'motorcycles' => 'motocicletas',
        'parts' => 'peças',
        'accessories' => 'acessórios',
        'tools' => 'ferramentas',
        'industrial' => 'industrial',
        'pet' => 'pet',
        'products' => 'produtos',
        'education' => 'educação',
        'school' => 'escola',
        'supplies' => 'materiais',
        'weddings' => 'casamentos',
        'events' => 'eventos',
        'novelty' => 'novidades',
        'special' => 'especial',
        'use' => 'uso',
        'outdoor' => 'ar livre',
        'entertainment' => 'entretenimento',
        'consumer' => 'consumo',
        'kitchen' => 'cozinha',
        'dining' => 'refeições',
        'bar' => 'bar',
        'festive' => 'festivo',
        'party' => 'festa',
        'arts' => 'artes',
        'crafts' => 'artesanato',
        'sewing' => 'costura',
        'textile' => 'têxtil',
        'fabric' => 'tecido',
        'muslim' => 'muçulmana',
        'fashion' => 'moda',
        'world' => 'mundial',
        'hair' => 'cabelo',
        'extensions' => 'extensões',
        'wigs' => 'perucas',
        'underwear' => 'roupas íntimas',
        'bottoms' => 'partes de baixo',
        'tops' => 'partes de cima',
        'sets' => 'conjuntos',
        'dresses' => 'vestidos',
        'laptops' => 'notebooks',
        'desktops' => 'computadores',
        'tablets' => 'tablets',
        'mobile' => 'móvel',
        'cellphones' => 'celulares',
        'cellphone' => 'celular',
        'networking' => 'redes',
        'storage' => 'armazenamento',
        'devices' => 'dispositivos',
        'components' => 'componentes',
        'peripherals' => 'periféricos',
    ];
    uksort($palavras, static function ($a, $b) {
        return strlen($b) <=> strlen($a);
    });
    foreach ($palavras as $ing => $pt) {
        $s = preg_replace('/\b' . preg_quote($ing, '/') . '\b/iu', $pt, $s);
    }
    return $s;
}
